# -*- coding: utf-8 -*-
"""Aula01-cerveja_machineLearning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VG7ldT29f6SxggmcF1wr2VC5iHexWT-T
"""

!pip install scikit-learn

import pandas as pd
from sklearn import tree

df = pd.read_excel("/content/data/dados_cerveja.xlsx")
df

features = ["temperatura", "copo", "espuma", "cor"]
target = "classe"

x = df[features]
y = df[target]

x = x.replace({"mud": 1 , "pint": 0 ,
               "sim" : 1 , "não": 0,
               "escura": 1, "clara": 0,})

arvore = tree.DecisionTreeClassifier(random_state=42)
arvore.fit(x, y)

import matplotlib.pyplot as plt

plt.figure(dpi=600)
tree.plot_tree(arvore, class_names=arvore.classes_,
               feature_names=features,
               filled=True)

probas = arvore.predict_proba([[-5,0,0,1]])
pd.Series(probas[0], index=arvore.classes_)